version: '3'
services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile-Api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - 3001:3000
    stdin_open: true
    tty: true

  react:
    build:
      context: .
      dockerfile: Dockerfile-Front
    command: bash -c "yarn start"
    ports:
      - 8001:3000
    depends_on:
      - rails
    stdin_open: true
    volumes:
      - ./react-app:/react-app
