version: '3'
services:
  rails:
    build:
      context: .
      dockerfile: Dockerfile-Api
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - /etc/passwd:/etc/passwd:ro # Linux用
      - /etc/group:/etc/group:ro # Linux用
    ports:
      - 3001:3000
    stdin_open: true
    tty: true

  react:
    build:
      context: .
      dockerfile: Dockerfile-Front
    environment:
      CHOKIDAR_USEPOLLING: 1 # hot reload is not working...
    command: bash -c "yarn start"
    ports:
      - 8001:3000
    depends_on:
      - rails
    stdin_open: true
    tty: true
    volumes:
      - ./react-app:/react-app
